apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  MONGO_HOSTNAME: "mongodb-0.mongodb.default.svc.cluster.local,mongodb-2.mongodb.default.svc.cluster.local,mongodb-3.mongodb.default.svc.cluster.local"
  MONGO_PORT: "27017"
  MONGO_DB: "kbtu-sa"
  MONGO_REPLICASET: "db"